services:
  superlink:
    command:
      - --insecure
      - --isolation
      - process
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --database=state/state.db
    # To toggle TLS encryption and persisting state for the SuperLink, comment the key `command`
    # above and uncomment the lines below:
    # command:
    # - --isolation
    # - process
    # - --host
    # - 0.0.0.0
    # - --port
    # - "8000"
    # - --ssl-ca-certfile=certificates/ca.crt
    # - --ssl-certfile=certificates/server.pem
    # - --ssl-keyfile=certificates/server.key
    # - --appio-ssl-ca-certfile=certificates/ca.crt
    # - --appio-ssl-certfile=certificates/server.pem
    # - --appio-ssl-keyfile=certificates/server.key
    # - --database=state/state.db
    volumes:
      - ./state/:/app/state/:rw
