services:
  superlink:
    image: flwr/superlink:${FLWR_VERSION:-1.37.0}
    command:
      - --isolation
      - process
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --ssl-ca-certfile=certificates/ca.crt
      - --ssl-certfile=certificates/server.pem
      - --ssl-keyfile=certificates/server.key
      - --appio-ssl-ca-certfile=certificates/ca.crt
      - --appio-ssl-certfile=certificates/server.pem
      - --appio-ssl-keyfile=certificates/server.key
      - --database=state/state.db
    volumes:
      - ./state/:/app/state/:rw
    secrets:
      - source: superlink-ca-certfile
        target: /app/certificates/ca.crt
      - source: superlink-certfile
        target: /app/certificates/server.pem
      - source: superlink-keyfile
        target: /app/certificates/server.key
    ports:
      - 9092:9092
      - 8000:8000

  superexec-serverapp:
    build:
      context: ${PROJECT_DIR:-.}
      dockerfile_inline: |
        FROM flwr/superexec:${FLWR_VERSION:-1.37.0}

        WORKDIR /app
        COPY --chown=app:app pyproject.toml LICENSE* ./
        RUN sed -i 's/.*flwr\[simulation\].*//' pyproject.toml \
          && python -m pip install -U --no-cache-dir .

        ENTRYPOINT ["flower-superexec"]
    command:
      - --root-certificates
      - certificates/superlink-ca.crt
      - --plugin-type
      - serverapp
      - --runtime-api-address
      - superlink:8000
    secrets:
      - source: superlink-ca-certfile
        target: /app/certificates/superlink-ca.crt
    depends_on:
      - superlink

secrets:
  superlink-ca-certfile:
    file: ../superlink-certificates/ca.crt
  superlink-certfile:
    file: ../superlink-certificates/server.pem
  superlink-keyfile:
    file: ../superlink-certificates/server.key
