# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Add connector lifecycle metadata.

Revision ID: f670d1ed8681
Revises: dfdbe2a8f936
Create Date: 2026-09-21 09:09:03.187252
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from flwr.supercore.state.schema.types import UTCDateTime

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "f670d1ed8681"
down_revision: str | Sequence[str] | None = "dfdbe2a8f936"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing account-scoped connectors cannot be mapped reliably to a federation.
    op.drop_table("connector")
    op.create_table(
        "connector",
        sa.Column("connector_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("federation_id", sa.String(), nullable=False),
        sa.Column("connector_ref", sa.String(), nullable=False),
        sa.Column("credentials_json", sa.String(), nullable=False),
        sa.Column("config_json", sa.String(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("deleted_at", UTCDateTime(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("deleted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("connector_id"),
        sa.UniqueConstraint("federation_id", "connector_ref"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("connector")
    op.create_table(
        "connector",
        sa.Column("flwr_aid", sa.String(), nullable=False),
        sa.Column("connector_ref", sa.String(), nullable=False),
        sa.Column("credentials_json", sa.String(), nullable=False),
        sa.Column("config_json", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("flwr_aid", "connector_ref"),
    )

    # ### end Alembic commands ###
