# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Support multiple connector accounts.

Revision ID: 8f4785e2dc47
Revises: 004925779532
Create Date: 2026-09-24 10:56:51.689972
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "8f4785e2dc47"
down_revision: str | Sequence[str] | None = "004925779532"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

CONNECTOR_UNIQUE_COLUMNS = {"federation_id", "connector_ref"}
CONNECTOR_UNIQUE_NAME = "uq_connector_federation_id_connector_ref"
NAMING_CONVENTION = {"uq": "uq_%(table_name)s_%(column_0_name)s_%(column_1_name)s"}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    unique_constraint = next(
        constraint
        for constraint in sa.inspect(bind).get_unique_constraints("connector")
        if set(constraint["column_names"]) == CONNECTOR_UNIQUE_COLUMNS
    )
    constraint_name = unique_constraint["name"] or CONNECTOR_UNIQUE_NAME
    with op.batch_alter_table(
        "connector",
        schema=None,
        naming_convention=NAMING_CONVENTION,
        table_kwargs={"sqlite_autoincrement": True},
    ) as batch_op:
        batch_op.drop_constraint(constraint_name, type_="unique")

    op.drop_table("run_connector")
    op.create_table(
        "run_connector",
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("connector_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("run_id", "connector_id"),
    )

    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.add_column(sa.Column("connector_id", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_column("connector_id")

    op.drop_table("run_connector")
    op.create_table(
        "run_connector",
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("connector_ref", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("run_id", "connector_ref"),
    )

    # The previous schema can retain only one account for each provider.
    op.execute(
        sa.text(
            """
            DELETE FROM connector
            WHERE connector_id NOT IN (
                SELECT MIN(connector_id) FROM connector
                GROUP BY federation_id, connector_ref
            )
            """
        )
    )
    with op.batch_alter_table(
        "connector",
        schema=None,
        table_kwargs={"sqlite_autoincrement": False},
    ) as batch_op:
        batch_op.create_unique_constraint(
            CONNECTOR_UNIQUE_NAME, ["federation_id", "connector_ref"]
        )

    # ### end Alembic commands ###
