# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Cache federation apps.

Revision ID: 91deea54ac6c
Revises: 94018fa20b10
Create Date: 2026-09-04 08:57:30.656869
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from flwr.supercore.state.schema.types import UTCDateTime

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "91deea54ac6c"
down_revision: str | Sequence[str] | None = "94018fa20b10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("federation_app", schema=None) as batch_op:
        batch_op.add_column(sa.Column("updated_at", UTCDateTime(), nullable=True))
    op.execute(sa.text("UPDATE federation_app SET updated_at = added_at"))
    op.execute(sa.text("DELETE FROM federation_app WHERE fab_hash IS NULL"))
    with op.batch_alter_table("federation_app", schema=None) as batch_op:
        batch_op.alter_column("fab_hash", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=UTCDateTime(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("federation_app", schema=None) as batch_op:
        batch_op.alter_column("fab_hash", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.drop_column("updated_at")

    # ### end Alembic commands ###
