# Copyright 2026 Flower Labs GmbH. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Allow Hub apps without a FAB hash.

Revision ID: 94018fa20b10
Revises: e4ecc602bd9a
Create Date: 2026-09-02 18:24:37.486564
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# pylint: disable=no-member

# revision identifiers, used by Alembic.
revision: str = "94018fa20b10"
down_revision: str | Sequence[str] | None = "e4ecc602bd9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("federation_app", schema=None) as batch_op:
        batch_op.alter_column("fab_hash", existing_type=sa.VARCHAR(), nullable=True)
    op.execute(
        sa.text("UPDATE federation_app SET fab_hash = NULL WHERE is_hub_app = TRUE")
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Older versions cannot represent Hub associations without a FAB hash. Remove
    # them instead of introducing an invalid empty hash; they can be added again.
    op.execute(sa.text("DELETE FROM federation_app WHERE fab_hash IS NULL"))
    with op.batch_alter_table("federation_app", schema=None) as batch_op:
        batch_op.alter_column("fab_hash", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###
